### ISSUE TITLE
Box URL API does not support CORS

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#112]
When a user is from another domain, the response header that contains URL information is not accessible.  

Suggestion:  
1. Fastest and easiest way is to put the URL in the response body.  
1. Return proper response headers which support CORS.  

>    {
>      "Url": "https://demo.personium.io/john.doe/schedule/"
>    }

## Other  Changes Required
Successful  Status Code: 204 -> 200
Box Url Ending Slash in Location Header:  no -> yes

**Comment by shimono** [comment]
https://personium.github.io/en/apiref/current/002_CORS_Support.html

**Comment by dixonsiu** [comment]
Actually the server must reply with the following response header so that JavaScript can access the header - "Location".  
[access-control-expose-headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)

**Comment by SawamiWataru** [comment]
Released in v1.6.6
