### ISSUE TITLE
Unify the setting place of path where event log is saved.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#126]
Current specifications.
- When creating log
  - Refer to "eventlog_path" in logback.xml
- When log is acquired
  - Refer to "io.personium.core.event.log.current.dir" in personium-unit-config.properties

---
eventログの書き込みと読み込みでそれぞれ異なる設定箇所のPathを参照している。
今はデフォルトで同一の設定になっているので問題ないが、ユーザがどちらかを修正すると正常に動作しなくなる。
修正：https://github.com/KourokiTakuto/personium-core/commit/1b2aa0735b05da3fbc7243f00f1d860afe1821c7 でcoreとしての修正は完了しているが、logback.xmlの修正によりansibleにも影響が出る。同時にリリースが必要。

**Comment by SawamiWataru** [comment]
It is difficult to fix where you are reading logback.xml.
I think that the following policy is good.
- Remove setting from personium-unit-config.properties
- Read log setting from logback.xml

The related sources are as follows.
- io.personium.core.event.EventUtils.getEventLogDir()
- io.personium.core.rule.action.LogAction

**Comment by KourokiTakuto** [comment]
The logback.xml setting value variable has been modified to refer to personium-unit-config.properties.
It is necessary to modify "Ansible" logback.xml.
Correct it also when modifying large "Ansible".

**Comment by yoh1496** [comment]
How about making `eventlog_path` contain `/personium_nfs/personium-core/eventlog/` and pass entire event log path which is loaded from personium-unit-config.properties ?

https://github.com/personium/personium-core/blob/v1.8.1/src/main/resources/logback.xml#L62

before
```xml
<file>/personium_nfs/personium-core/eventlog/${eventlog_path}/current/default.log</file>
```

after
```xml
<file>${eventlog_path}/current/default.log</file>
```
