### ISSUE TITLE
Can't set personium-localcell:/__ctl/Role to EventObject on rule with _Box.Name.

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-core#177]
Currently EventObject of rule with _Box.Name is allowed to set personium-localbox:/xxx only.
But Object for cell control object's operations can't express by personium-localbox:/.
Therefore make personium-localcell:/__xxx available on EventObject of rule with _Box.Name.

**Comment by SawamiWataru** [comment]
Released v1.6.7
