### ISSUE TITLE
Replace control chars in resource names when creating a new file or directory

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#217]
Currently any string including control codes can be used as DAV collection / file names.
Control codes should be excluded when creating DAV file / collection resources. 

---
現在コレクション名とファイル名は入力された文字列をそのまま適用している。
制御コードを入力不可にして、マルチバイト文字を指定したい場合はURLエンコードしたものを入力する仕様に変更する。
現状実際に制御コードなどを入れたときにどういう挙動をするかまでは未確認。

**Comment by shimono** [comment]
Currently,

> io.personium.core.model.DavCommon.isValidResourceName(String)


checks the resource name when creating a resource.

**Comment by shimono** [comment]
Useful references:
https://www.baeldung.com/java-validate-filename
https://www.jpcert.or.jp/java-rules/ids05-j.html

**Comment by shimono** [comment]
https://stackoverflow.com/questions/6198986/how-can-i-replace-non-printable-unicode-characters-in-java
https://minory.org/java-ascii-control-character.html

`my_string.replaceAll("\\p{C}", "?");`
