### ISSUE TITLE
Support per-Cell FQDN

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#223]
Items that need to be modified.
- [x] API endpoint after CellLevel
- [x] Change cell naming convention
- [x] WebSocket connection endpoint
- [x] Issuer judgment of UnitUser
- [x] Token endpoint "client_id","p_target"
- [x] Authorization endpoint "client_id","p_target"
- [x] Box "Schema"
- [x] base_url in ACL settings xml
- [ ] Location header of API response
- [x] Test code
- [ ] It does not work when URL format is switched during service
- [ ] ExtCell can double registration with new URL format and old URL format

Modification of API reference personium/api-references#164

**Comment by shimono** [comment]
Memo:

We need to introduce new URL scheme

personium-localunit:/dixonsiu  
personium-localunit:/__ctl/Cell

personium-localunitcell:dixonsiu:/box1/


Before
------------
demo.personium.io/dixsonsiu
demo.personium.io/shimono


after
dixsonsiu.demo.personium.io
shimono.demo.personium.io
