### ISSUE TITLE
GET against Cell root URL should return HomeApp HTML

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#234]
# Purpose
For easier use of Personium, GET request against Cell root URL should return HomeApp HTML. When you type your Cell URL in your browser address bar, Home App should open.

# Change Outline
GET request against Cell root URL currently return an XML. Let us change like the following way. 

- When Accept Header is application/xml, current XML should be returned
- In other cases, check the property <p:relayHtmlUrl> text value 
- if it is valid URL, then GET the URL content and relay back to the client.
- In the following cases,  error HTML should be returned.
-- if the property is not configured  
-- if  the value is not a valid HTTPS URL 
-- if the response Content-Type is not text/html

# Where to change

CellResource,

**Comment by SawamiWataru** [comment]
Released v1.6.14.
