### ISSUE TITLE
GET against authorization endpoint should return relayed HTML content from preconfigured remote URL

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#235]
## Background
In order to fully support OAuth 2.0 authorization endpoint,  the returned HTML should be customizable by Cell owner.

## Purpose
Let the HTML from authorization endpoint be relayed HTML from preconfigured URL.

# Change Outline
GET request against authorization endpoint URL currently return fixed HTML. Let us change like the following way. 

- When authorization endpoint needs to return HTML,
- check the cell root URL's DAV property <p:authorizationHtmlUrl> text value 
- if it is valid URL, then GET the URL content and relay back to the client.
- In the following cases,  current default HTML should be returned.
-- if the property is not configured  
-- if the value is not a valid HTTPS URL 
-- if the response Content-Type is not text/html

# Where to change

AuthorizationEndpointResource

**Comment by SawamiWataru** [comment]
Released v1.6.14.
