### ISSUE TITLE
BAR installation incorrectly assigns CollectionKind to "NONE" 

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#272]
BAR installation incorrectly assigns CollectionKind to "NONE". The expected value should be "None".

[Related issue](https://github.com/personium/app-uc-unit-manager/issues/137) in Unit Manager.

**Comment by shimono** [comment]
https://github.com/personium/personium-core/blob/7c15227cf66c9c5002023d1c5de855c8dafc36d2/src/main/java/io/personium/core/model/ctl/Property.java#L40

https://github.com/personium/personium-core/blob/master/src/main/java/io/personium/core/bar/BarFileContentsInstallVisitor.java#L722

**Comment by shimono** [comment]
All capitalized "NONE" should be a bug in odata4j since CSDL spec says

> In CSDL 1.1, CSDL 1.2, CSDL 2.0, and CSDL 3.0, a Property element can define a
> CollectionKind attribute. The possible values are "None", "List", and "Bag". 
> 

https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MC-CSDL/%5bMC-CSDL%5d-170316.pdf

**Comment by SawamiWataru** [comment]
Released v1.7.6
