### ISSUE TITLE
When multiple accesses to the same Box occurred, 500 Errors occurred

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#28]
When multiple accesses to the same Box occurred, 500 Errors occurred.

PR500-DV-0002: Dav system inconsistency detected.

**Comment by SawamiWataru** [comment]
### Personium behavior
- Failed to get .pmeta file
- .pmeta file is generated the first time you execute the API targeted under Box after Box creation
- .pmeta file is created under the Box directory after creating it
- If the Box directory exists, obtain the .pmeta file under it

### Cause
The phenomenon is reproduced when executing API which accesses under Box at the same time after creating Box.

Assume that API to be executed concurrently is [API-1] [API-2].
A phenomenon occurs when the following processing order is reached.

1. [API-1] Determine presence / absence of Box directory (Box directory does not exist)
2. [API-1] Create Box directory
3. [API-2] Determine presence / absence of Box directory (Box directory exists)
4. [API-2] Obtain .pmeta file (error occurred because .pmeta file does not exist)
5. [API-1] Create .pmeta file

**Comment by hideakikondo** [comment]
Solved in v1.5.2
