### ISSUE TITLE
Default value of Accept Header is not 'application/json'

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-core#282]
'application/atom+xml' is default.

e.g.
```
     curl {CellURL}__ctl/Role -H 'Authorization:Bearer ...' -i
```

**Comment by shimono** [comment]
As specified in the following OData v2.0 spec, atom+xml should be the default content-type.
https://www.odata.org/documentation/odata-version-2-0/operations/#RepresentationFormatAndContentTypeNegotiation
