### ISSUE TITLE
Introduce Stream Collection and add new Action 'relay.data' to Rule.

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-core#289]
New Feature
----------
Introduce Stream Collection in order to deal with data that changes moment by moment.
Stream Collection don't store data unlike OData Collection.
Stream Collection has two types:
- Queue
- Topic

Queue is used when relationship between sender and receiver is one to one.
Topic is used when relationship between sender and receiver is one to many. Sender can broadcast data to many receivers.

Enhancement
----------
Add new Action 'relay.data' to Rule.
'relay.data' copy data written to odata(EventObject) to TargetUrl.
TargetUrl can set not only OData Collection but also Stream Collection.

**Comment by SawamiWataru** [comment]
Released v1.7.5
