### ISSUE TITLE
Import Cells repeatedly without destroy one of the previously imported Cell

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#307]
# How to reproduce the bug  
Repeat the following 4 times (app-minimal-clone, app-minimal-clone02, app-minimal-clone03, app-minimal-clone04), app-minimal-clone02 will become an empty Cell and Role/Account are deleted.  
1. Create a Cell  
1. Upload a zip file which is created from another Personium Unit  
1. Perform import

**Comment by dixonsiu** [comment]
# Suggested solution  
Allow user to export with two (2) different options.  
1. export all data but only import once  
1. export only resource without data but allow importing more than once

**Comment by SawamiWataru** [comment]
This issue is closed as it is no longer triggered by the #423 fix.
