### ISSUE TITLE
Add information when issuing tokens.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#309]
Parameters to add
- "Last_succeed_time": last login success date and time
- "Failed_count": Number of authentication failures since last login success

**Comment by Akira-Ohishi** [comment]
rename additional properties.
(fit the name of an existing propertys.)

"last_authenticated": last login success date and time
"failed_count": Number of authentication failures since last login success

**Comment by Akira-Ohishi** [comment]
Account "LastAuthenticated"
abolish.

**Comment by SawamiWataru** [comment]
Released v1.7.5
