### ISSUE TITLE
Quit converting Cell URL to path-base in the Issuer& Subject fields in Tokens

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#334]
# Overview
Currently  Cell URLs in the Issuer and Subject fields in Access / Refresh Tokens are converted to 
path-base Url even if the unit is configured as Per-Cell FQDN mode. This behavior was originally introduced as a provisional countermeasure for hybrid URL usage where it is difficult to distinguish the following 3 types of URLs.

1. Unit URL
1. Cell URL
1. Box URL

Now that the above issue is resolved by the introduction of the Cell metadata API, we should quit 
Quit converting Cell URL to path-base in the Issuer& Subject fields in Tokens.

## Note 
By quitting the conversion, interoperability between the units 1.7.x before quitting and ones after quitting will be lost.

**Comment by SawamiWataru** [comment]
related issue #336

**Comment by SawamiWataru** [comment]
Released v1.7.5
