### ISSUE TITLE
Improve error output level when installing bar files.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#34]
## problem
Even in the case of a user operation error, it is output at the ERROR level.

## solution
For user operation error, output at INFO level.

---
ユーザ操作ミスで起きる可能性のあるログがErrorレベルで出力されている箇所がある。
Infoレベルに修正すべき。
このIssueではbarインストールが対象になっているが、全般的に見直すのが良いと思われる。

**Comment by shimono** [comment]
This seems to have been fixed already.
