### ISSUE TITLE
Introduce Status property to Account

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#340]
# Overview
Introduce "Status" property to the cell control object "Account".

# Valid Values 

|Value|Default|Description|
|:--|:--|:--|
|active|Y|Normal and active account|
|suspended|-|temporarily suspended account. Although the credential is kept valid, authentication will always fail. |

# PUT / MERGE

The "Status" property value can be updated with PUT/MERGE operation.

**Comment by Akira-Ohishi** [comment]
Change "suspended" to "deactivated".

**Comment by Akira-Ohishi** [comment]
MERGE is not currently supported.
Since it also relates to other than "status", we will take another correspondence.

**Comment by SawamiWataru** [comment]
Released v1.7.7
