### ISSUE TITLE
Support MERGE of the cell management object.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#351]

**Comment by Akira-Ohishi** [comment]
"Cell management object" indicates the following.- Account
- Role
- ExtCell
- Relation
- ExtRole
- Box
- Rule

**Comment by Akira-Ohishi** [comment]
#### About Rule
There is an input restriction due to multiple items.
When MERGE is performed, there is a risk of becoming an unintended value other than the update item.
Rule can not be MERGE because it is not realistic.

**Comment by SawamiWataru** [comment]
Released v1.7.14
