### ISSUE TITLE
URLs in link element in XML return value is not escaped

### ISSUE THREAD

**Issue by Yonezawa-T2** [personium/personium-core#372]
When access to `https://CELL/__ctl/ExtCell('OTHER_CELL')` and the return value is an XML, href attribute of link elements are not encoded.

Example: `<link rel="edit" title="ExtCell" href="ExtCell('https://foo.example.org/')" />`

Expected: `<link rel="edit" title="ExtCell" href="ExtCell('https%3A%2F%2Ffoo.example.org%2F')" />`

URLs in JSON format are encoded as expected (#214).

**Comment by SawamiWataru** [comment]
Released v1.7.9
