### ISSUE TITLE
Token acquisition API should respond with info which Account has been authenticated 

### ISSUE THREAD

**Issue by hideakikondo** [personium/personium-core#39]
* Problem
When you try to get an access token with Open ID Connect (e.g. Google) authentication API, the request parameter does not contain Account name.
Therefore, a client application cannot take information which Account authenticated.

* Solution
`X-Personium-Authenticated-Account` response header would be added to Token acquisition API.

**Comment by hideakikondo** [comment]
case: 
grant_type = password => The same value of request parameter "username=XXX"
grant_type = oidc:google =>Gmail address in decoded ID token value.

**Comment by shimono** [comment]
The aim of this issue will be achieved through the following issue fix;
https://github.com/personium/personium-core/issues/281

So I am closing this issue.
