### ISSUE TITLE
Concurrent request support for token authentication to the same account(App cell). 

### ISSUE THREAD

**Issue by Akira-Ohishi** [personium/personium-core#398]
When token authentication to the same account occurs frequently, the error "Too many concurrent requests" occurs.
This is because the record of authentication history is waiting for unlocking by exclusive control of file update.

App cells share and use a specific account. There is no need to keep records of certification history as it is meaningless.
In order to prevent "Too many concurrent requests" from occurring with the above-mentioned accounts, we modify it to be able to specify the account which does not leave the record of the authentication history for every cell.

**Comment by SawamiWataru** [comment]
Released v1.7.12_es6.6.1
