### ISSUE TITLE
Update httpclient lib version.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#41]
- Delete unused libraries
- Review library version

**Comment by hideakikondo** [comment]
Please check [this document (in Japanese)](https://github.com/fujitsu-pio/docs-draft-ja/wiki/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E9%96%93%E3%81%AE%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82) about dependencies of modules just for reference.

**Comment by SawamiWataru** [comment]
Urgent response
To avoid library conflicts, we only upgrade httpclient of engine.

**Comment by SawamiWataru** [comment]
Released in 1.6.0.
