### ISSUE TITLE
Created/updated timestamps are saved in JST

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#42]
To support overseas client, it should be UTC.

For example, in Wakaba Client App's  lm.isExpired, we tried to compare the expiry date of the timestamp with current time. If the application is executed in machine that use US time, we will have the wrong result.

**Comment by shimono** [comment]
I think it is saved in UTC format internally.  Probably you are talking about PROPFIND result.
PROPFIND response rendering somehow converts to local time format.

**Comment by shimono** [comment]
https://github.com/personium/personium-core/blob/93105d9491c6366e3c6f2686034ebc9bee204f33/src/main/java/io/personium/core/model/DavRsCmp.java#L506

Plz see above, Yes, It is handled in unix time interanally. but org.apache.wink.webdav.model.Getlastmodified automatically change to local time format.

I remember we took i18n (timezone) in consideration on initial implementation, also.
We found out that wink library automatically converts to local date and could not find the way to force it to return in utc time.  And considering the fact that it still returns timezone info in the format, we gave up and made it clients' responsibility to properly handle the info obtained from the server (time w/ timezone info) and present to user in preferable way (covert in accordance with client timezone)

**Comment by shimono** [comment]
Sorry i am not the one to close this issue.

Dixonsiu, if you are satisfied with the above answer, plz close this issue.

**Comment by dixonsiu** [comment]
Which machine's local time do you refer to?  

1. Personium Unit
1. User PC

Correct me if I am wrong. We will have problem with the following cases.  
Personium Unit using Japan UTC and convert to Japan local time when replying to PROFIND. However, user is in London and the PC's time is London time. There will be problem comparing London local time to Japan local time.
