### ISSUE TITLE
Incorrect argument is passed to constructor ODataResource().

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-core#44]
It is necessary to add '/' after getUrl().

https://github.com/personium/personium-core/blob/master/src/main/java/io/personium/core/rs/box/ODataSvcCollectionResource.java#L58
https://github.com/personium/personium-core/blob/master/src/main/java/io/personium/core/rs/box/ODataSvcSchemaResource.java#L80-L82

**Comment by shimono** [comment]
Could you add information about why it is necessary?  I guess some API may be returning strange URL like:
` https://example.com/john/box1/col//odata/entset`

**Comment by nisiguti** [comment]
Current value of rootUrl member in ODataResource class is as follows.
  https://example.com/john/box1col/
But any trouble has not occurred, because this rootUrl is not used currently.

**Comment by SawamiWataru** [comment]
Solved in v1.5.4.
