### ISSUE TITLE
If `__id` of OData results contain `/`, `__metadata.uri` is not escaped.

### ISSUE THREAD

**Issue by Yonezawa-T2** [personium/personium-core#486]
If `__id` of OData results contain `/`, `__metadata.uri` is not escaped.

For example, getting a user-defined OData EntitySet `Foo` returns the following JSON:

```
{
  "d": {
    "results": [
      {
        "__metadata": {
          "uri": "https://cell.example.org/__/odata/Foo('https://aaa.example.org/')",
          ...
        },
        "__id": "https://aaa.example.org/",
        ...
      }
    ]
  }
}
```

May related: #372, #214
Personium Version: 1.7.18

**Comment by shimono** [comment]
Looks like an easy simple bug fix. So I want to fix it quickly.
