### ISSUE TITLE
DateTime properties are handled as text properties for range query 

### ISSUE THREAD

**Issue by Yonezawa-T2** [personium/personium-core#487]
Querying OData entities with `$filter` on `DateTime` properties results in incorrect answer when it spans `2001-09-10`.

Example: querying with `$filter=birthday ge datetime'1960-01-01T00:00:00' and birthday le datetime'2001-09-10T00:00:00'`, where `birthday` is a custom property with type `DateTime`, results in an empty result even if matching entities exists.

As `2001-09-09` is the day UNIX time over 1000000000, I guess Personium searches `DateTime` properties as text properties.

Investing `__mappings` of Elasticsearch shows that Personium indexes all custom properties as `text`, as well as `keyword`, `long`, and `double` using multi-fields feature (`fields`).

Seeing [`getSuffix` in `UserDataQueryHandler.java`](https://github.com/personium/personium-core/blob/bd5568adad87b38a8788fe27dd77aed98c815d51/src/main/java/io/personium/core/model/impl/es/odata/UserDataQueryHandler.java#L136-L147) shows that if EDM type is `SINGLE` or `DOUBLE`, Personium use `double` field and if EDM type is `INT32`, it use `long` field. Otherwise, including when the type is `DateTime`, it use `text` field.

The type of the Lucene query Elasticsearch dispatches depends on the field type, not the type of values in actual documents, nor type of query parameters.
https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-range-query.html

So, while DateTime properties are stored as numbers (Unix time) in documents, it is searched as text properties, I guess.

**Comment by shimono** [comment]
Thank you for raising this issue with detailed source code analyses. We will put high priority for fixing this.
