### ISSUE TITLE
BAR file 90_rootprops.xml should not use a "personium-localunit:" URL.

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#512]
## Error  
Latest release that supports "personium-localunit:" literrals fail when installing BAR file.

![BarImportError](https://user-images.githubusercontent.com/29846750/68276592-b0e0fb80-00b0-11ea-9b5c-796f4109ea7e.png)

## Error message from Unit Manager  
```
{
    "schema": "https://app-myboard.appdev.personium.io/",
    "name": "appdev",
    "started_at": "2019-11-06T07:05:14.959Z",
    "progress": "66%",
    "message": {
        "code": "PL-BI-1004",
        "message": {
            "lang": "en",
            "value": "Installation failed([90_rootprops.xml] file format error.)."
        }
    },
    "url": "https://dixonsiu.appdev.personium.io/appdev/",
    "status": "installation failed"
}
```
## Expected behaviour  
acl tag should allow new format of URL.

**Comment by shimono** [comment]
A base URL in the bar file rootprops.xml should not be in a form with personium-localunit scheme.

It should instead be in the following form.
```
{schemaUrl}__role/__/
```
