### ISSUE TITLE
"Unknown Exception" has occurred on $select query for CellCtl object.

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-core#56]
The table below is the result of each CellCtl object.
Existent key is the property name that an object has. For example, existent key of Role are "Name" and "_Box.Name". Non-existent key is a name that an object does not have. For example, "hoge" for Role.

|object|existent key|non-existent key|
|:--|:--|:--|
|Role|Unknown Exception|Unknown Exception|
|Account|OK|Unknown Exception|
|Box|OK|Unknown Exception|
|ExtCell|OK|Unknown Exception|
|Relation|Unknown Exception|Unknown Exception|
|ExtRole|Unknown Exception|Unknown Exception|

When "Unknown Exception" results, NPE has occurred on server.
If data for object is empty, "Unknown Exception" does not result. 

Are these results correct?

**Comment by nisiguti** [comment]
|object|existent key|non-existent key|
|:--|:--|:--|
|Role|Unknown Exception|Unknown Exception|
|Account|OK|Unknown Exception|
|Box|OK|Unknown Exception|
|ExtCell|OK|Unknown Exception|
|Relation|Unknown Exception|Unknown Exception|
|ExtRole|Unknown Exception|Unknown Exception|
|Rule|Unknown Exception|Unknown Exception|

**Comment by nisiguti** [comment]
NPE on existent key because variable links is null. This is a bug to fix.
NPE on non-existent key because result of query is empty. I think this is a specification bug.
api-references described "If you specify a property name that does not exist in $select, ignore the specified item". I think response should be empty.

**Comment by nisiguti** [comment]
'Unknown Exception' has occurred on $expand query too.

**Comment by SawamiWataru** [comment]
This issue is resolved by the fix of #295.
