### ISSUE TITLE
developer onboarding improvements

### ISSUE THREAD

**Issue by j1n6** [personium/personium-core#577]
This is a suggestion of improving developer onboarding. 

### Objective Assumptions

**As a new application developer for Personium:**

1) need a quick way to obtain/request an account to be created. The account requires to be associated with at least one unit and cell. The application also require a unique domain name created. 
2) need a visual way to understand how configurations can be applied to application - i.e. a section shows my CELL, USER, FQDN, etc so that it's easier for the devs to understand how to map them to application settings. 
3) a section to show how to get started (e.g. examples linking to github, sdks for the programming languages) 

**As a unit/cell service provider:**
1) would prefer to ensure resources consumption is manageable. At this stage, the service is built for testing and demonstration only. Thus, creating demo account needs to be controlled via an approval process.

2) structurally receive request that has been validated by the system; user should be able to pick a preferred/unique unit/cell name. Service provide will approve the demo account creation instead of using slack request channel. 

3) Account and resources can be released if the account hasn't been used for over a time period
   e.g. 3 months no activities -> move to achieve -> email notification to the unit owner 
          2 months no achieve retrieval -> move to delete -> email notification to the unit owner 

**As an organisation who may provide services to internal developers:**
1) Reduce the need of manual operations internally to support developers and internal adoption.

**Comment by j1n6** [comment]
@shimono @dixonsiu 
This came from my experience when getting started to pick up the knowledge (aka. eating my own dog food), what's your thoughts?

**Comment by tochi-y** [comment]
@j1n6 Thank you for your suggestions. I agree with your comments. We will improve our documentation and the operations of the demo environment based on your comments. Thanks!
