### ISSUE TITLE
Change Servlet Spec from 3.0 to 3.1 

### ISSUE THREAD

**Issue by hideakikondo** [personium/personium-core#6]
# Problem

Currently our web.xml defines our apps (core/engine) are written in the form of servlet spec 3.0.  We use Tomcat 8 in development and testing and recommend users to use it,  however according to the following information, tomcat 8 is for servlet spec 3.1.
http://tomcat.apache.org/whichversion.html

This may cause minor issues. 
# Solution

Change web.xml to use servlet spec 3.1.

**Comment by SawamiWataru** [comment]
Released v1.6.16
