### ISSUE TITLE
Enable "Edm.Double" for declared user properties.

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#67]
# Current Problem
- In our OData Service Collection, Edm.Double is used only when Number data is posted in JSON format upon creation of an entity. 
-  You can only choose Edm.Single, and can not choose Edm.Double when defining schema, i.e., creating a Property or in the EDMX in bar files.

# Situation 
- Personium core can handle Edm.Double internally since it can be used in Dynamic Properties.
- In the validation phase of schema definition, it just does not recognize  Edm.Double.

# remedy
Just let it recognize  Edm.Double at schema definition.

- [ ] when creating "Property" (url : ../odata/$metadata/Property) 
- [ ] In the EDMX file in bar files  

# additional tasks
- [ ] update API reference

**Comment by SawamiWataru** [comment]
I checked the current source code and behavior.
Currently it already allows Edm.Double create.
The only thing to do is to modify the API reference.

**Comment by SawamiWataru** [comment]
I have created an API reference correction issue.
https://github.com/personium/api-references/issues/30

I will close this issue.
