### ISSUE TITLE
Recursive delete of  WebDAV collection without user OData.

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#68]
When DELETE method request with X-Personium-Recursive is issued against a plain WebDAV collection with contents without OData Servcie Collections, it should delete it together with the contents.

Additional consideration would be necessary if ACL "deny"  was already implemented. But let us forget about it now since it is not yet done, and think about it when we implement ACL "deny".

**Comment by shimono** [comment]
Let us not exclude Engine Service Collection, also. They are just files and folders internally. 
So exclusion requires extra consideration.

**Comment by SawamiWataru** [comment]
Solved in v1.5.7.
