### ISSUE TITLE
API to retrieve role/relation info for certain user (token)

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-core#93]
Currently, we need to send a GET/PUT request to see if read/write permission is granted or not.  

It is better to know in advance.  
Parameter: Source User's access_token, target URL of resource which Source User want to access
~~Return value: Boolean (true/false)~~
Return value: hash of role/relation info

**Comment by SawamiWataru** [comment]
Token Introspection Endpointの提供によりCloseとする。
https://personium.io/docs/ja/apiref/current/297_OAtuh2_Token_Introspection_Endpoint.html
