### ISSUE TITLE
Modify API execution privilege of NullResource.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#95]
Example
#### PROPFIND
- Current  implementation
  - checkAccessContext(this.davRsCmp.getAccessContext(), BoxPrivilege.READ);
- Correct  implementation
  - checkAccessContext(this.davRsCmp.getAccessContext(), BoxPrivilege.READ_PROPERTIES);

#### PROPPATCH
- Current  implementation
  - checkAccessContext(this.davRsCmp.getAccessContext(), BoxPrivilege.WRITE);
- Correct  implementation
  - checkAccessContext(this.davRsCmp.getAccessContext(), BoxPrivilege.WRITE_PROPERTIES);

**Comment by shimono** [comment]
"read" is superior privilege of read-properties, i.e. read includes read-properties. So it should go like:

PROPFIND
  - OK :read
  - OK :read-properties

GET
  - OK :read
  - NG :read-properties

**Comment by SawamiWataru** [comment]
Sorry. I made a misunderstanding writing style.
The description was corrected.

**Comment by SawamiWataru** [comment]
Released in 1.6.1.
